### ISSUE TITLE
Bed Texture is wrong

### ISSUE THREAD

**Issue by Haui1112** [newtoallofthis123/NS-Texture#2]
The bed texture (white bed if that makes any difference) is not correct. Breaking and building again doesnt change anything. different orientation doesnt do anything either.

![screenshot_20240304_145033](https://github.com/newtoallofthis123/NS-Texture/assets/109665179/3b65f261-af09-4ce0-bcdf-24fca512f327)
![screenshot_20240304_145030](https://github.com/newtoallofthis123/NS-Texture/assets/109665179/2a5a0caa-ad5b-48de-8a60-76e7f176c476)

**Comment by newtoallofthis123** [comment]
Yes I am aware of this issue @Haui1112. The way minetest renders bed has changed in a recent version and I'll try and put up a change to it...feel free to make it if you are interested :)

**Comment by Haui1112** [comment]
I'm already done fixing the issues I opened. Just need to repack and open a PR. 

Should we change to a filetree and only make the release a zip? That way one can just upload a texture.

**Comment by newtoallofthis123** [comment]
that is exactly what we did @Haui1112 😄 

Thanks for the contribution! Just updated my own texture :)
